name: Read YouTube titles
on:
  push:
    paths:
      - '.github/workflows/read-youtube-titles.yml'
jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - name: Read metadata
        run: |
          curl -fsSL 'https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=VvSIj9rhanA&format=json'
          curl -fsSL 'https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=9gjRkeIT4Uo&format=json'
          curl -fsSL 'https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=K1INgUGwwQU&format=json'
